### ISSUE TITLE
libfuzzer-base: checkout alternative way to compile

### ISSUE THREAD

**Issue by ikisusi** [ouspg/libfuzzerfication#1]
Currently there is a for loop in libfuzzer-base Dockerfile:

```
for f in /src/llvm/lib/Fuzzer/*cpp; do /work/llvm/bin/clang++ -std=c++11 -IFuzzer -c $f; done
```

Couldn't this be replaced with?

```
/work/llvm/bin/clang++ -c -g -O2 -std=c++11 /src/llvm/lib/Fuzzer/*.cpp -IFuzzer
```

As per http://llvm.org/docs/LibFuzzer.html#building.

Furthermore adding:

```
cd /src/llvm/lib/Fuzzer
ar ruv libFuzzer.a Fuzzer*.o
```

Would allow replacing `/work/libfuzzer/*.o` constructs in `build.sh`-scripts with `/path/to/libFuzzer.a`, or even `-lFuzzer` if the archive would be placed in library search path.

**Comment by oherrala** [comment]
Library location fixed in #4
