### ISSUE TITLE
Samples and results are written out from container with root permissions.

### ISSUE THREAD

**Issue by attekett** [ouspg/libfuzzerfication#12]
All files that are written out to the mounted volumes have default permissions set:

> -rw-r--r--  1 root     root          /samples/f91c14ee3598a92c2d7e0fe3ac479006013eb6d9
> 
> -rw-r--r--  1 root     root          /samples/fbd5fb18fb67b24e67cefb884553485550d419c9

This can cause issues with users that don't have root access to the machine they are using. (And is really annoying.)

We have to find a way to set the permissions to reflect the user running the container.

**Comment by mikkoyli** [comment]
https://denibertovic.com/posts/handling-permissions-with-docker-volumes/

**Comment by mikkoyli** [comment]
Maybe solution to problem: https://docs.docker.com/machine/reference/scp/

**Comment by WhiteEyeDoll** [comment]
Seconded. docker-machine scp is both cleaner and much more robust solution for this.

**Comment by attekett** [comment]
If we promote docker scp, we have to provide someway for the user to do parallel fuzzing.
