### ISSUE TITLE
Have a most wanted/kill list for the targets

### ISSUE THREAD

**Issue by ikisusi** [ouspg/libfuzzerfication#26]
Lets have a easily accessible list developed out from the protocode data and possibly other sources/opinions. List should have the target, has it been fuzzed (if yes, by whom and how much?), is there a libfuzzer stub available (and where?), does something still need to be done (and by us or is help needed?).

**Comment by mikkoyli** [comment]
https://docs.google.com/spreadsheets/d/1oj0L44gKTn3wlrJk6b554b9o8H0r1bVfb6LJrw62BEE/pubhtml
