### ISSUE TITLE
Learn Docker memory limit from cgroups

### ISSUE THREAD

**Issue by oherrala** [ouspg/libfuzzerfication#47]
It's possible to see memory limit inside docker container:

File `/sys/fs/cgroup/memory/memory.stat` has `hierarchical_memory_limit` which gives container's max memory

``` console
$ docker run -ti -m 4g --rm ubuntu:latest grep hierarchical_memory_limit /sys/fs/cgroup/memory/memory.stat
hierarchical_memory_limit 4294967296

$ docker run -ti -m 2g --rm ubuntu:latest grep hierarchical_memory_limit /sys/fs/cgroup/memory/memory.stat
hierarchical_memory_limit 2147483648
```

`fuzz.sh` could use this to set the memory limit.

**Comment by mikkoyli** [comment]
docker-compose:
-rss_limit_mb=4096' not needed in docker-compose?
-default values for fuzz.sh that can be overrided

**Comment by mikkoyli** [comment]
related to #88
