### ISSUE TITLE
Add sample files to each stub

### ISSUE THREAD

**Issue by mikkoyli** [ouspg/libfuzzerfication#49]
Add some samples to each stub
- [x] ImageMagick
- [x] haskell-x509
- [x] libav
- [x] libmad
- [x] libxml2
- [x] libxslt
- [x] lua
- [x] mysamplelib
- [x] zlib

**Comment by mikessu** [comment]
use lfs

**Comment by mikkoyli** [comment]
Samples for libav cannot be added before it works correctly.
