### ISSUE TITLE
Building haskell doesn't work with docker-compose

### ISSUE THREAD

**Issue by mikkoyli** [ouspg/libfuzzerfication#66]
Building haskell-x509
Step 1 : FROM ouspg/libfuzzer-base-haskell
Pulling repository docker.io/ouspg/libfuzzer-base-haskell
ERROR: Service 'haskell-x509' failed to build: Error: image ouspg/libfuzzer-base-haskell not found

**Comment by WhiteEyeDoll** [comment]
Image repo for libfuzzer-base-haskell did not exist.
Created autobuild for the image.
